// <auto-generated />
namespace MyCommunity.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removedsomething : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedsomething));
        
        string IMigrationMetadata.Id
        {
            get { return "201610191711579_removed something"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
