// <auto-generated />
namespace MyCommunity.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dateadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dateadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201610131950181_date added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
